favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5961599606089294
  brandStrength: 1
  rhythmicContrast: 0.7312100995332003
  brandColors:
    - '#434D4C'
    - '#2B3939'
    - '#11191B'
    - '#6E7D6A'
    - '#A89766'
  lightness: 0.8196589783765376
typography_spectrum: 0.8978494
layout_spectrum: 0.5053763
analytics:
  twitter: null
  google: null
  facebook: null
name: notpill
