name: notpill
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49772
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: notpill
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#434D4C'
    - '#2B3939'
    - '#11191B'
    - '#6E7D6A'
    - '#A89766'
  brandStrength: 0
  lightness: 0
  saturation: 0.5961599606089294
  rhythmicContrast: 0.7312100995332003
purpose: []
